import { createAction } from "redux-actions";
import { CATEGORY } from "../actionTypes/category";
export const getAllCategoriesAction = createAction(CATEGORY.GETALL);
export const getAllCategoriesSuccessAction = createAction(CATEGORY.GETALL_SUCCESS);
export const getAllCategoriesFailureAction = createAction(CATEGORY.GETALL_FAILURE);
export const getByIdCategoryAction = createAction(CATEGORY.GETBYID);
export const getByIdCategorySuccessAction = createAction(CATEGORY.GETBYID_SUCCESS);
export const getByIdCategoryFailureAction = createAction(CATEGORY.GETBYID_FAILURE);
export const changeStatusCategoryAction = createAction(CATEGORY.CHANGE_STATUS);
export const changeStatusCategorySuccessAction = createAction(CATEGORY.CHANGE_STATUS_SUCCESS);
export const changeStatusCategoryFailureAction = createAction(CATEGORY.CHANGE_STATUS_FAILURE);
export const deleteCategoryAction = createAction(CATEGORY.DELETE);
export const deleteCategorySuccessAction = createAction(CATEGORY.DELETE_SUCCESS);
export const deleteCategoryFailureAction = createAction(CATEGORY.DELETE_FAILURE);
export const addCategoryAction = createAction(CATEGORY.ADD);
export const addCategorySuccessAction = createAction(CATEGORY.ADD_SUCCESS);
export const addCategoryFailureAction = createAction(CATEGORY.ADD_FAILURE);
export const editCategoryAction = createAction(CATEGORY.EDIT);
export const editCategorySuccessAction = createAction(CATEGORY.EDIT_SUCCESS);
export const editCategoryFailureAction = createAction(CATEGORY.EDIT_FAILURE);