import { createAction } from "redux-actions";
import { ROLE } from "../actionTypes/role";
export const getAllRolesAction = createAction(ROLE.GETALL);
export const getAllRolesSuccessAction = createAction(ROLE.GETALL_SUCCESS);
export const getAllRolesFailureAction = createAction(ROLE.GETALL_FAILURE);
export const getByIdRoleAction = createAction(ROLE.GETBYID);
export const getByIdRoleSuccessAction = createAction(ROLE.GETBYID_SUCCESS);
export const getByIdRoleFailureAction = createAction(ROLE.GETBYID_FAILURE);
export const changeStatusRoleAction = createAction(ROLE.CHANGE_STATUS);
export const changeStatusRoleSuccessAction = createAction(ROLE.CHANGE_STATUS_SUCCESS);
export const changeStatusRoleFailureAction = createAction(ROLE.CHANGE_STATUS_FAILURE);
export const deleteRoleAction = createAction(ROLE.DELETE);
export const deleteRoleSuccessAction = createAction(ROLE.DELETE_SUCCESS);
export const deleteRoleFailureAction = createAction(ROLE.DELETE_FAILURE);
export const addRoleAction = createAction(ROLE.ADD);
export const addRoleSuccessAction = createAction(ROLE.ADD_SUCCESS);
export const addRoleFailureAction = createAction(ROLE.ADD_FAILURE);
export const editRoleAction = createAction(ROLE.EDIT);
export const editRoleSuccessAction = createAction(ROLE.EDIT_SUCCESS);
export const editRoleFailureAction = createAction(ROLE.EDIT_FAILURE);