export const CAPACITY = {
  GETALL: "CAPACITY_GETALL",
  GETALL_SUCCESS: "CAPACITY_GETALL_SUCCESS",
  GETALL_FAILURE: "CAPACITY_GETALL_FAILURE",

  GETBYID: "CAPACITY_GETBYID",
  GETBYID_SUCCESS: "CAPACITY_GETBYID_SUCCESS",
  GETBYID_FAILURE: "CAPACITY_GETBYID_FAILURE",

  CHANGE_STATUS: "CAPACITY_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "CAPACITY_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "CAPACITY_CHANGE_STATUS_FAILURE",

  DELETE: "CAPACITY_DELETE",
  DELETE_SUCCESS: "CAPACITY_DELETE_SUCCESS",
  DELETE_FAILURE: "CAPACITY_DELETE_FAILURE",

  ADD: "CAPACITY_ADD",
  ADD_SUCCESS: "CAPACITY_ADD_SUCCESS",
  ADD_FAILURE: "CAPACITY_ADD_FAILURE",
  
  EDIT: "CAPACITY_EDIT",
  EDIT_SUCCESS: "CAPACITY_EDIT_SUCCESS",
  EDIT_FAILURE: "CAPACITY_EDIT_FAILURE",
};