export const CAR = {
  GETALL: "CAR_GETALL",
  GETALL_SUCCESS: "CAR_GETALL_SUCCESS",
  GETALL_FAILURE: "CAR_GETALL_FAILURE",

  GETBYID: "CAR_GETBYID",
  GETBYID_SUCCESS: "CAR_GETBYID_SUCCESS",
  GETBYID_FAILURE: "CAR_GETBYID_FAILURE",

  CHANGE_STATUS: "CAR_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "CAR_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "CAR_CHANGE_STATUS_FAILURE",

  DELETE: "CAR_DELETE",
  DELETE_SUCCESS: "CAR_DELETE_SUCCESS",
  DELETE_FAILURE: "CAR_DELETE_FAILURE",

  ADD: "CAR_ADD",
  ADD_SUCCESS: "CAR_ADD_SUCCESS",
  ADD_FAILURE: "CAR_ADD_FAILURE",
  
  EDIT: "CAR_EDIT",
  EDIT_SUCCESS: "CAR_EDIT_SUCCESS",
  EDIT_FAILURE: "CAR_EDIT_FAILURE",
 
  GETALL_SELECT: "CAR_GETALL_SELECT",
  GETALL_SELECT_SUCCESS: "CAR_GETALL_SELECT_SUCCESS",
  GETALL_SELECT_FAILURE: "CAR_GETALL_SELECT_FAILURE",
};