export const DRIVER = {
  GETALL: "DRIVER_GETALL",
  GETALL_SUCCESS: "DRIVER_GETALL_SUCCESS",
  GETALL_FAILURE: "DRIVER_GETALL_FAILURE",

  GETBYID: "DRIVER_GETBYID",
  GETBYID_SUCCESS: "DRIVER_GETBYID_SUCCESS",
  GETBYID_FAILURE: "DRIVER_GETBYID_FAILURE",

  CHANGE_STATUS: "DRIVER_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "DRIVER_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "DRIVER_CHANGE_STATUS_FAILURE",

  DELETE: "DRIVER_DELETE",
  DELETE_SUCCESS: "DRIVER_DELETE_SUCCESS",
  DELETE_FAILURE: "DRIVER_DELETE_FAILURE",

  ADD: "DRIVER_ADD",
  ADD_SUCCESS: "DRIVER_ADD_SUCCESS",
  ADD_FAILURE: "DRIVER_ADD_FAILURE",
  
  EDIT: "DRIVER_EDIT",
  EDIT_SUCCESS: "DRIVER_EDIT_SUCCESS",
  EDIT_FAILURE: "DRIVER_EDIT_FAILURE",
 
  GETALL_SELECT: "DRIVER_GETALL_SELECT",
  GETALL_SELECT_SUCCESS: "DRIVER_GETALL_SELECT_SUCCESS",
  GETALL_SELECT_FAILURE: "DRIVER_GETALL_SELECT_FAILURE",
};