export const IMAGE = {
  IMAGE_GETBYID: "IMAGE_GETBYID",
  IMAGE_GETBYID_SUCCESS: "IMAGE_GETBYID_SUCCESS",
  IMAGE_GETBYID_FAILURE: "IMAGE_GETBYID_FAILURE",
  IMAGE_DELETE: "IMAGE_DELETE",
  IMAGE_DELETE_SUCCESS: "IMAGE_DELETE_SUCCESS",
  IMAGE_DELETE_FAILURE: "IMAGE_DELETE_FAILURE",
  IMAGE_ADD: "IMAGE_ADD",
  IMAGE_ADD_SUCCESS: "IMAGE_ADD_SUCCESS",
  IMAGE_ADD_FAILURE: "IMAGE_ADD_FAILURE",
};