export const PERMISSIONROLES = {
  //GETALL
  GETALL: "PERMISSIONROLES_GETALL",
  GETALL_SUCCESS: "PERMISSIONROLES_GETALL_SUCCESS",
  GETALL_FAILURE: "PERMISSIONROLES_GETALL_FAILURE",
  //GETBYID
  GETBYID: "PERMISSIONROLES_GETBYID",
  GETBYID_SUCCESS: "PERMISSIONROLES_GETBYID_SUCCESS",
  GETBYID_FAILURE: "PERMISSIONROLES_GETBYID_FAILURE",
  //CHANGE_STATUS
  CHANGE_STATUS: "PERMISSIONROLES_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "PERMISSIONROLES_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "PERMISSIONROLES_CHANGE_STATUS_FAILURE",
  //DELETE
  DELETE: "PERMISSIONROLES_DELETE",
  DELETE_SUCCESS: "PERMISSIONROLES_DELETE_SUCCESS",
  DELETE_FAILURE: "PERMISSIONROLES_DELETE_FAILURE",
  //ADD
  ADD: "PERMISSIONROLES_ADD",
  ADD_SUCCESS: "PERMISSIONROLES_ADD_SUCCESS",
  ADD_FAILURE: "PERMISSIONROLES_ADD_FAILURE",
  //EDIT
  EDIT: "PERMISSIONROLES_EDIT",
  EDIT_SUCCESS: "PERMISSIONROLES_EDIT_SUCCESS",
  EDIT_FAILURE: "PERMISSIONROLES_EDIT_FAILURE",
};