export const PRICE = {
  GETALL: "PRICE_GETALL",
  GETALL_SUCCESS: "PRICE_GETALL_SUCCESS",
  GETALL_FAILURE: "PRICE_GETALL_FAILURE",

  GETBYID: "PRICE_GETBYID",
  GETBYID_SUCCESS: "PRICE_GETBYID_SUCCESS",
  GETBYID_FAILURE: "PRICE_GETBYID_FAILURE",

  CHANGE_STATUS: "PRICE_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "PRICE_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "PRICE_CHANGE_STATUS_FAILURE",

  DELETE: "PRICE_DELETE",
  DELETE_SUCCESS: "PRICE_DELETE_SUCCESS",
  DELETE_FAILURE: "PRICE_DELETE_FAILURE",

  ADD: "PRICE_ADD",
  ADD_SUCCESS: "PRICE_ADD_SUCCESS",
  ADD_FAILURE: "PRICE_ADD_FAILURE",

  EDIT: "PRICE_EDIT",
  EDIT_SUCCESS: "PRICE_EDIT_SUCCESS",
  EDIT_FAILURE: "PRICE_EDIT_FAILURE",

  FILTER: "PRICE_FILTER",
  FILTER_SUCCESS: "PRICE_FILTER_SUCCESS",
  FILTER_FAILURE: "PRICE_FILTER_FAILURE",
};