export const PRICEADJUSTMENT = {
  GETALL: "PRICEADJUSTMENT_GETALL",
  GETALL_SUCCESS: "PRICEADJUSTMENT_GETALL_SUCCESS",
  GETALL_FAILURE: "PRICEADJUSTMENT_GETALL_FAILURE",

  GETBYID: "PRICEADJUSTMENT_GETBYID",
  GETBYID_SUCCESS: "PRICEADJUSTMENT_GETBYID_SUCCESS",
  GETBYID_FAILURE: "PRICEADJUSTMENT_GETBYID_FAILURE",

  CHANGE_STATUS: "PRICEADJUSTMENT_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "PRICEADJUSTMENT_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "PRICEADJUSTMENT_CHANGE_STATUS_FAILURE",

  DELETE: "PRICEADJUSTMENT_DELETE",
  DELETE_SUCCESS: "PRICEADJUSTMENT_DELETE_SUCCESS",
  DELETE_FAILURE: "PRICEADJUSTMENT_DELETE_FAILURE",

  ADD: "PRICEADJUSTMENT_ADD",
  ADD_SUCCESS: "PRICEADJUSTMENT_ADD_SUCCESS",
  ADD_FAILURE: "PRICEADJUSTMENT_ADD_FAILURE",

  EDIT: "PRICEADJUSTMENT_EDIT",
  EDIT_SUCCESS: "PRICEADJUSTMENT_EDIT_SUCCESS",
  EDIT_FAILURE: "PRICEADJUSTMENT_EDIT_FAILURE",
};