export const REPORT = {
  BANGKE: "REPORT_BANGKE",
  BANGKE_SUCCESS: "REPORT_BANGKE_SUCCESS",
  BANGKE_FAILURE: "REPORT_BANGKE_FAILURE",

  CHECK_BANGKE: "REPORT_CHECK_BANGKE",
  CHECK_BANGKE_SUCCESS: "REPORT_CHECK_BANGKE_SUCCESS",
  CHECK_BANGKE_FAILURE: "REPORT_CHECK_BANGKE_FAILURE",
};