export const TRANSPORTATION = {
  GETALL: "TRANSPORTATION_GETALL",
  GETALL_SUCCESS: "TRANSPORTATION_GETALL_SUCCESS",
  GETALL_FAILURE: "TRANSPORTATION_GETALL_FAILURE",

  GETBYID: "TRANSPORTATION_GETBYID",
  GETBYID_SUCCESS: "TRANSPORTATION_GETBYID_SUCCESS",
  GETBYID_FAILURE: "TRANSPORTATION_GETBYID_FAILURE",

  CHANGE_STATUS: "TRANSPORTATION_CHANGE_STATUS",
  CHANGE_STATUS_SUCCESS: "TRANSPORTATION_CHANGE_STATUS_SUCCESS",
  CHANGE_STATUS_FAILURE: "TRANSPORTATION_CHANGE_STATUS_FAILURE",

  DELETE: "TRANSPORTATION_DELETE",
  DELETE_SUCCESS: "TRANSPORTATION_DELETE_SUCCESS",
  DELETE_FAILURE: "TRANSPORTATION_DELETE_FAILURE",

  ADD: "TRANSPORTATION_ADD",
  ADD_SUCCESS: "TRANSPORTATION_ADD_SUCCESS",
  ADD_FAILURE: "TRANSPORTATION_ADD_FAILURE",
  
  EDIT: "TRANSPORTATION_EDIT",
  EDIT_SUCCESS: "TRANSPORTATION_EDIT_SUCCESS",
  EDIT_FAILURE: "TRANSPORTATION_EDIT_FAILURE",

  GENERATEMONEY: "TRANSPORTATION_GENERATEMONEY",
  GENERATEMONEY_SUCCESS: "TRANSPORTATION_GENERATEMONEY_SUCCESS",
  GENERATEMONEY_FAILURE: "TRANSPORTATION_GENERATEMONEY_FAILURE",

  FILTER: "TRANSPORTATION_FILTER",
  FILTER_SUCCESS: "TRANSPORTATION_FILTER_SUCCESS",
  FILTER_FAILURE: "TRANSPORTATION_FILTER_FAILURE",

  UPDATE_MONEY: "TRANSPORTATION_UPDATE_MONEY",
  UPDATE_MONEY_SUCCESS: "TRANSPORTATION_UPDATE_MONEY_SUCCESS",
  UPDATE_MONEY_FAILURE: "TRANSPORTATION_UPDATE_MONEY_FAILURE",
};