//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inputed incorrect!.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user success!  Assign default role fail!.
        /// </summary>
        public static string CreateUserSuccessAndAssignRoleFail {
            get {
                return ResourceManager.GetString("CreateUserSuccessAndAssignRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user success! Assign default role success!.
        /// </summary>
        public static string CreateUserSuccessAndAssignRoleSuccess {
            get {
                return ResourceManager.GetString("CreateUserSuccessAndAssignRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role for {0} error!.
        /// </summary>
        public static string ErrorAssignRole {
            get {
                return ResourceManager.GetString("ErrorAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status {0} error!.
        /// </summary>
        public static string ErrorChangeStatus {
            get {
                return ResourceManager.GetString("ErrorChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check is exist!.
        /// </summary>
        public static string ErrorCheckIsExist {
            get {
                return ResourceManager.GetString("ErrorCheckIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is invalid!.
        /// </summary>
        public static string ErrorCheckValidUserName {
            get {
                return ResourceManager.GetString("ErrorCheckValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm account {0} error!.
        /// </summary>
        public static string ErrorConfirmAccount {
            get {
                return ResourceManager.GetString("ErrorConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} error!.
        /// </summary>
        public static string ErrorCreate {
            get {
                return ResourceManager.GetString("ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} error!.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} error because children existed!.
        /// </summary>
        public static string ErrorDeleteExistChild {
            get {
                return ResourceManager.GetString("ErrorDeleteExistChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all {0} error!.
        /// </summary>
        public static string ErrorGetAll {
            get {
                return ResourceManager.GetString("ErrorGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} by id error!.
        /// </summary>
        public static string ErrorGetById {
            get {
                return ResourceManager.GetString("ErrorGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} error!.
        /// </summary>
        public static string ErrorRemove {
            get {
                return ResourceManager.GetString("ErrorRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove role for {0} error!.
        /// </summary>
        public static string ErrorRemoveRole {
            get {
                return ResourceManager.GetString("ErrorRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} error!.
        /// </summary>
        public static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not empty!.
        /// </summary>
        public static string FieldCanNotEmpty {
            get {
                return ResourceManager.GetString("FieldCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is existed!.
        /// </summary>
        public static string FieldIsExisted {
            get {
                return ResourceManager.GetString("FieldIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid!.
        /// </summary>
        public static string FieldIsInvalid {
            get {
                return ResourceManager.GetString("FieldIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is valid!.
        /// </summary>
        public static string FieldIsValid {
            get {
                return ResourceManager.GetString("FieldIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password!.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username!.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failure: Invalid username or password!.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is existed in the system!.
        /// </summary>
        public static string KeyIsExisted {
            get {
                return ResourceManager.GetString("KeyIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is valid!.
        /// </summary>
        public static string KeyIsValid {
            get {
                return ResourceManager.GetString("KeyIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found data!.
        /// </summary>
        public static string NotFoundData {
            get {
                return ResourceManager.GetString("NotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found this {0} id!.
        /// </summary>
        public static string NotFoundId {
            get {
                return ResourceManager.GetString("NotFoundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is deleted!.
        /// </summary>
        public static string ObjectIsDeleted {
            get {
                return ResourceManager.GetString("ObjectIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is existed!.
        /// </summary>
        public static string ObjectIsExisted {
            get {
                return ResourceManager.GetString("ObjectIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path file can not empty!.
        /// </summary>
        public static string PathFileNotEmpty {
            get {
                return ResourceManager.GetString("PathFileNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email error!.
        /// </summary>
        public static string SendEmailError {
            get {
                return ResourceManager.GetString("SendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email success!.
        /// </summary>
        public static string SendEmailSuccess {
            get {
                return ResourceManager.GetString("SendEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SheetNameDefault.
        /// </summary>
        public static string SheetNameDefault {
            get {
                return ResourceManager.GetString("SheetNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role for {0} success!.
        /// </summary>
        public static string SuccessAssignRole {
            get {
                return ResourceManager.GetString("SuccessAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status {0} success!.
        /// </summary>
        public static string SuccessChangeStatus {
            get {
                return ResourceManager.GetString("SuccessChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check is not exist!.
        /// </summary>
        public static string SuccessCheckIsExist {
            get {
                return ResourceManager.GetString("SuccessCheckIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is valid!.
        /// </summary>
        public static string SuccessCheckValidUserName {
            get {
                return ResourceManager.GetString("SuccessCheckValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirm success for user id &quot;{0}&quot;!.
        /// </summary>
        public static string SuccessConfirmAccount {
            get {
                return ResourceManager.GetString("SuccessConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} success!.
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} success!.
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all {0} success!.
        /// </summary>
        public static string SuccessGetAll {
            get {
                return ResourceManager.GetString("SuccessGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} by id success! .
        /// </summary>
        public static string SuccessGetById {
            get {
                return ResourceManager.GetString("SuccessGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success!.
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} success!.
        /// </summary>
        public static string SuccessRemove {
            get {
                return ResourceManager.GetString("SuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove role for {0} success!.
        /// </summary>
        public static string SuccessRemoveRole {
            get {
                return ResourceManager.GetString("SuccessRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} success!.
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have at least one role!.
        /// </summary>
        public static string UserMustHaveRole {
            get {
                return ResourceManager.GetString("UserMustHaveRole", resourceCulture);
            }
        }
    }
}
